"""add  row

Revision ID: 69fd2b86c755
Revises: 9a4493f057d0
Create Date: 2021-08-17 22:00:10.519274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fd2b86c755'
down_revision = '9a4493f057d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
