"""add name column in the pitch schema

Revision ID: ca33eb89acd7
Revises: 18bcaa3e8bf9
Create Date: 2021-08-16 20:35:29.201404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca33eb89acd7'
down_revision = '18bcaa3e8bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###
