"""empty message

Revision ID: cc3444698bf1
Revises: ca33eb89acd7
Create Date: 2021-08-17 20:38:09.329366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3444698bf1'
down_revision = 'ca33eb89acd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pitches_timestamp'), 'pitches', ['timestamp'], unique=False)
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'downvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pitches_timestamp'), table_name='pitches')
    op.drop_column('pitches', 'timestamp')
    # ### end Alembic commands ###
